services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./certs/key.pem:/etc/nginx/ssl/key.pem:ro
